name: CICD Pipeline

on:
  push:
    branches:
      - main


jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Display node.js version
        run: node -v

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run check

  
  Deploy:
    runs-on: [self-hosted, github-action-runner-2]
    needs: Testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version

      - name: Verify Node.js version
        run: node --version
 
      - name: Install Dependencies
        run: npm install

      - name: Install pm2 
        run: sudo npm install -g pm2
 
      - name: Deploy to Server
        run: |
          pwd
          pm2 delete "Server" || true
          pm2 start "npm run dev" --name="Server"

      - name: Install NGINX
        run: |
          sudo apt update
          sudo apt install nginx -y
          sudo systemctl status nginx --no-pager

      - name: Configure NGINX Proxy Pass
        run: |
          sudo tee /etc/nginx/sites-available/your_domain > /dev/null <<'EOF'
          server {
              listen 80;
              server_name _;
          
              location / {
                  proxy_pass http://localhost:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
          EOF

      - name: Remove default site link
        run: |
          sudo rm -f /etc/nginx/sites-enabled/default
      
      - name: Enable the new site configuration
        run: |
          sudo ln -s /etc/nginx/sites-available/your_domain /etc/nginx/sites-enabled/
      
      - name: Test Nginx configuration
        run: |
          sudo nginx -t
      
      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx
      
      - name: Check Nginx status
        run: |
          sudo systemctl status nginx --no-pager